### ISSUE TITLE
link in readme is a dead link

### ISSUE THREAD

**Issue by letzfets** [Brightspace/util-api-test-tool#9]

**Comment by j3parker** [comment]
This one https://apitesttool.desire2learnvalence.com ? Works for me.

**Comment by letzfets** [comment]
Not in safari:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/44865639/98275699-3a156180-1f95-11eb-9523-8f866aa930ef.png">

works in chrome!

**Comment by j3parker** [comment]
Not a Danish speaker or Safari user but I think that's saying there was a protocol error... it looks like we are serving this site over HTTP/2... what version of Safari are you using?

FYI @jordankay13 -- I think you run this tool?

**Comment by letzfets** [comment]
Ohh my bad - I totally forgot, that there are still fellow human being, that don't speak Danish 🇩🇰 yet. 😉

Well, the error says:
**Safari cannot open the page**
Safari cannot open the page. The error is: "Request cannot be processed. Protokolerror"

My Safari version is: Version 14.0 (15610.1.28.1.9, 15610)

**Comment by richmar10** [comment]
> Not a Danish speaker or Safari user but I think that's saying there was a protocol error... it looks like we are serving this site over HTTP/2... what version of Safari are you using?
> 
> FYI @jordankay13 -- I think you run this tool?

@j3parker  We're looking into this issue as well as some deployment updates.

**Comment by j3parker** [comment]
Thanks @richmar10 !
